#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=40gb,walltime=08:00:00

#[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

#export SINGULARITYENV_WORKDIR=$(pwd)

## modules
#echo "Loading modules"
#module unload python
#module load dipy/dev
#module load nodejs
#module load singularity
#echo "Finished loading modules"

#export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

#echo "setting miniconda path..."
#unset PYTHONPATH
#export PATH=/N/u/gberto/Karst/miniconda2/bin:$PATH 

set -e
set -x

segmentations=`jq -r '.segmentations' config.json`
arr_seg=()
arr_seg+=(${segmentations})
num_ex=$((${#arr_seg[@]} - 2))

#execute app
if [ $num_ex -le 0 ]; then
	echo "No examples provided. STARTING TEST..."
	./run_test.sh
else
	echo $num_ex "examples provided. STARTING TRAINING & TEST..."
	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 ./run.sh
fi

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.nii.gz -f
rm *.tck
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f
rm prototypes.npy -f

echo "Complete"
