#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=16gb,walltime=00:10:00

set -e
set -x

segmentations=`jq -r '.segmentations' config.json`
arr_seg=()
arr_seg+=(${segmentations})
num_ex=$((${#arr_seg[@]} - 2))

#execute app
if [ $num_ex -le 0 ]; then
	echo "No examples provided. STARTING TEST..."
	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 ./run_test.sh
	#SINGULARITYENV_PYTHONNOUSERSITE=true  singularity exec docker://brainlife/dipy:1.1.1 ./run_test.sh
else
	echo $num_ex "examples provided. STARTING TRAINING & TEST..."
	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 ./run.sh
	#SINGULARITYENV_PYTHONNOUSERSITE=true  singularity exec docker://brainlife/dipy:1.1.1 ./run.sh
fi

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.nii.gz -f
rm *.tck
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f

echo "Complete"

